# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AIService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AIService.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x41IService.proto\x12\x07\x65xample\"3\n\rDetectRequest\x12\n\n\x02Id\x18\x01 \x01(\t\x12\x16\n\x0eshouldStudents\x18\x02 \x01(\t\"%\n\x0b\x44\x65tectReply\x12\x16\n\x0e\x61\x63tualStudents\x18\x01 \x01(\t\"%\n\x10RecognizeRequest\x12\x11\n\tstudentId\x18\x01 \x01(\t\"#\n\x0eRecognizeReply\x12\x11\n\tencodings\x18\x01 \x01(\t2\x8b\x01\n\x04\x46\x61\x63\x65\x12<\n\nFaceDetect\x12\x16.example.DetectRequest\x1a\x14.example.DetectReply\"\x00\x12\x45\n\rFaceRecognize\x12\x19.example.RecognizeRequest\x1a\x17.example.RecognizeReply\"\x00\x62\x06proto3'
)




_DETECTREQUEST = _descriptor.Descriptor(
  name='DetectRequest',
  full_name='example.DetectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='example.DetectRequest.Id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shouldStudents', full_name='example.DetectRequest.shouldStudents', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=79,
)


_DETECTREPLY = _descriptor.Descriptor(
  name='DetectReply',
  full_name='example.DetectReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='actualStudents', full_name='example.DetectReply.actualStudents', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=118,
)


_RECOGNIZEREQUEST = _descriptor.Descriptor(
  name='RecognizeRequest',
  full_name='example.RecognizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='studentId', full_name='example.RecognizeRequest.studentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=157,
)


_RECOGNIZEREPLY = _descriptor.Descriptor(
  name='RecognizeReply',
  full_name='example.RecognizeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='encodings', full_name='example.RecognizeReply.encodings', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=194,
)

DESCRIPTOR.message_types_by_name['DetectRequest'] = _DETECTREQUEST
DESCRIPTOR.message_types_by_name['DetectReply'] = _DETECTREPLY
DESCRIPTOR.message_types_by_name['RecognizeRequest'] = _RECOGNIZEREQUEST
DESCRIPTOR.message_types_by_name['RecognizeReply'] = _RECOGNIZEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectRequest = _reflection.GeneratedProtocolMessageType('DetectRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETECTREQUEST,
  '__module__' : 'AIService_pb2'
  # @@protoc_insertion_point(class_scope:example.DetectRequest)
  })
_sym_db.RegisterMessage(DetectRequest)

DetectReply = _reflection.GeneratedProtocolMessageType('DetectReply', (_message.Message,), {
  'DESCRIPTOR' : _DETECTREPLY,
  '__module__' : 'AIService_pb2'
  # @@protoc_insertion_point(class_scope:example.DetectReply)
  })
_sym_db.RegisterMessage(DetectReply)

RecognizeRequest = _reflection.GeneratedProtocolMessageType('RecognizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZEREQUEST,
  '__module__' : 'AIService_pb2'
  # @@protoc_insertion_point(class_scope:example.RecognizeRequest)
  })
_sym_db.RegisterMessage(RecognizeRequest)

RecognizeReply = _reflection.GeneratedProtocolMessageType('RecognizeReply', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZEREPLY,
  '__module__' : 'AIService_pb2'
  # @@protoc_insertion_point(class_scope:example.RecognizeReply)
  })
_sym_db.RegisterMessage(RecognizeReply)



_FACE = _descriptor.ServiceDescriptor(
  name='Face',
  full_name='example.Face',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=197,
  serialized_end=336,
  methods=[
  _descriptor.MethodDescriptor(
    name='FaceDetect',
    full_name='example.Face.FaceDetect',
    index=0,
    containing_service=None,
    input_type=_DETECTREQUEST,
    output_type=_DETECTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FaceRecognize',
    full_name='example.Face.FaceRecognize',
    index=1,
    containing_service=None,
    input_type=_RECOGNIZEREQUEST,
    output_type=_RECOGNIZEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACE)

DESCRIPTOR.services_by_name['Face'] = _FACE

# @@protoc_insertion_point(module_scope)
