# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import AIService_pb2 as AIService__pb2


class FaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FaceDetect = channel.unary_unary(
                '/example.Face/FaceDetect',
                request_serializer=AIService__pb2.DetectRequest.SerializeToString,
                response_deserializer=AIService__pb2.DetectReply.FromString,
                )
        self.FaceRecognize = channel.unary_unary(
                '/example.Face/FaceRecognize',
                request_serializer=AIService__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=AIService__pb2.RecognizeReply.FromString,
                )


class FaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FaceDetect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FaceRecognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FaceDetect': grpc.unary_unary_rpc_method_handler(
                    servicer.FaceDetect,
                    request_deserializer=AIService__pb2.DetectRequest.FromString,
                    response_serializer=AIService__pb2.DetectReply.SerializeToString,
            ),
            'FaceRecognize': grpc.unary_unary_rpc_method_handler(
                    servicer.FaceRecognize,
                    request_deserializer=AIService__pb2.RecognizeRequest.FromString,
                    response_serializer=AIService__pb2.RecognizeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.Face', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Face(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FaceDetect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.Face/FaceDetect',
            AIService__pb2.DetectRequest.SerializeToString,
            AIService__pb2.DetectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FaceRecognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.Face/FaceRecognize',
            AIService__pb2.RecognizeRequest.SerializeToString,
            AIService__pb2.RecognizeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
